language: bash

addons:
  apt:
    update: true

services:
  - docker

install:
  - mkdir -p ssl
  - openssl req -x509 -nodes -keyout ./ssl/default.key -out ./ssl/default.crt -subj '/CN=localhost'
  - docker build --tag nginx-proxy .
  - docker run --detach --publish 80:80 --name nginx-proxy --volume ./ssl:/opt/ssl:ro nginx-proxy
  - sleep 10

script:
  - docker exec nginx-proxy nginx -t
